language: ruby
rvm:
- 2.0.0
deploy:
  provider: heroku
  api_key:
    secure: WsDDdiQ/zxuGBDMFMNdGszYPnulLSiHVUXnfcuH5iDQqv3IjoTpYCJ2NQaMC2oeXIiJLtBi7/wlTvvY3m/9Wp4HUSO1etUCX6Iu4AOYbMSwyJZQDXVHRfHPirh3nbq/DQYSQbalG4tRdelblrQMCYh16Re34bS6JbzAxtMZbXYE=
  app: pivotal-life-acceptance
  on:
    repo: spilth/pivotal-life
